# This is a basic workflow to help you get started with Actions

name: Build package

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["Run tests" ]
    types: [completed]

env:
  isProduction: 'false'
  MAJOR_VERSION: 1
  MINOR_VERSION: 0
  PATCH_VERSION: 0


jobs:
  validation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - run: echo 'The triggering workflow passed'

      - name: echo github context
        run: echo ${{ github.event.workflow_run.id }}

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'

      - name: Npm tool install
        run: npm install -g npm@8

              - name: Npm run build
        run: npm run build

      - name: Npm run generate-doc
        run: npm run generate-doc

      - name: store versions to txt files
        run: |
          echo ${{ env.MAJOR_VERSION }}.${{ env.MAJOR_VERSION }}.${{ env.PATCH_VERSION }} > production_version.txt
          echo  ${{ env.MAJOR_VERSION }}.${{ env.MAJOR_VERSION }}.${{ env.PATCH_VERSION }}--preview-${{ github.run_id }} > preview_version.txt
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist
            ./.npmrc
            ./package.json
            ./README.md
            ./LICENSE
            ./production_version.txt
            ./preview_version.txt

