name: lf-repository-api-client-js-CI

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  API_VERSION: 'v2'
  NPM_VERSION: '1.0.0'
  GITHUB_PAGES_BRANCH: 'gh-pages'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: dummy
      NPM_USERNAME: dummy
      NPM_EMAIL: dummy
      NPM_REGISTRY: dummy
    steps:
      - uses: actions/checkout@v2

      - name: Echo build number
        run: echo ${{github.run_id}}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"

      - name: NPM tool install
        run: npm install -g npm@8

      - name: NPM ci
        run: npm ci

      - name: NPM run build
        run: npm run build

      - name: Echo NPM package version
        run: echo ${{ env.NPM_VERSION }}

      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: npm-publish-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./dist
            ./package.json
            ./README.md
            ./LICENSE


  build-documentation:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"

      - name: NPM tool install
        run: npm install -g npm@8

      - name: NPM ci
        run: npm ci

      - name: NPM run build
        run: npm run build

      - name: Install typedoc
        run: npm install typedoc

      - name: Create temporary directory
        run: mkdir -p ./docs_temp

      - name: Generate typedoc docs
        run: npx typedoc ./src/index.ts --out ./docs_temp --excludePrivate --includeVersion

      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: documentation-artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ github.workspace }}/docs_temp

      - name: Delete temporary directory
        run: rm -r ./docs_temp

  publish-preview-package:
    runs-on: ubuntu-latest
    environment: preview
    if: ${{ github.run_attempt != 1 }}
    needs: [build, test, build-documentation] # wait for build to finish
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Download a build artifact
        uses: actions/download-artifact@v2.1.0
        with:
          name: npm-publish-artifact

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"

      - name: NPM tool install
        run: npm install -g npm@8

      - name: Set NpmPackageVersion as preview version from downloaded artifact
        run: echo "NpmPackageVersion=${{ env.NPM_VERSION }}--preview-${{ github.run_id }}" >> $GITHUB_ENV

      - name: NPM version
        run: npm version ${{ env.NpmPackageVersion }} --no-git-tag-version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: NPM publish
        run: npm publish  --access public  --tag next
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
          NPM_REGISTRY: ${{ secrets.NPM_REGISTRY }}

      - name: Tag commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.API_VERSION }}-${{ env.NpmPackageVersion }}
          commit_sha: ${{ github.sha }}
          message: Workflow run ${{github.server_url}}/${{github.repository}}/actions/runs/${{ github.run_id}}